{{- if .Values.rbac.create }}
{{- range $adapterName, $adapter := .Values.adapters }}
{{- if $adapter.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hyperfleet-adapter.serviceAccountName" (merge (dict "adapterType" $adapterName) $) }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "hyperfleet-adapter.adapterLabels" (merge (dict "adapterType" $adapterName) $) | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
